In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [36]:
api_call_1 = pd.read_csv('./doce_octubre/doce_octubre_1.csv')
api_call_2 = pd.read_csv('./doce_octubre/doce_octubre_2.csv')
api_call_3 = pd.read_csv('./doce_octubre/doce_octubre_3.csv')
api_call_4 = pd.read_csv('./doce_octubre/doce_octubre_4.csv')
api_call_5 = pd.read_csv('./doce_octubre/doce_octubre_5.csv')
api_call_6 = pd.read_csv('./doce_octubre/doce_octubre_6.csv')
api_call_7 = pd.read_csv('./doce_octubre/doce_octubre_7.csv')
api_call_8 = pd.read_csv('./doce_octubre/doce_octubre_8.csv')
api_call_9 = pd.read_csv('./doce_octubre/doce_octubre_9.csv')
api_call_10 = pd.read_csv('./doce_octubre/doce_octubre_10.csv')
api_call_11 = pd.read_csv('./doce_octubre/doce_octubre_11.csv')
api_call_12 = pd.read_csv('./doce_octubre/doce_octubre_12.csv')
api_call_13 = pd.read_csv('./doce_octubre/doce_octubre_13.csv')
api_call_14 = pd.read_csv('./doce_octubre/doce_octubre_14.csv')
api_call_15 = pd.read_csv('./doce_octubre/doce_octubre_15.csv')
api_call_16 = pd.read_csv('./doce_octubre/doce_octubre_16.csv')
api_call_17 = pd.read_csv('./doce_octubre/doce_octubre_17.csv')
api_call_18 = pd.read_csv('./doce_octubre/doce_octubre_18.csv')
api_call_19 = pd.read_csv('./doce_octubre/doce_octubre_19.csv')
api_call_20 = pd.read_csv('./doce_octubre/doce_octubre_20.csv')
api_call_21 = pd.read_csv('./doce_octubre/doce_octubre_21.csv')
api_call_22 = pd.read_csv('./doce_octubre/doce_octubre_22.csv')
api_call_23 = pd.read_csv('./doce_octubre/doce_octubre_23.csv')
api_call_24 = pd.read_csv('./doce_octubre/doce_octubre_24.csv')
api_call_25 = pd.read_csv('./doce_octubre/doce_octubre_25.csv')
api_call_26 = pd.read_csv('./doce_octubre/doce_octubre_26.csv')
api_call_27 = pd.read_csv('./doce_octubre/doce_octubre_27.csv')
api_call_28 = pd.read_csv('./doce_octubre/doce_octubre_28.csv')
api_call_29 = pd.read_csv('./doce_octubre/doce_octubre_29.csv')
api_call_30 = pd.read_csv('./doce_octubre/doce_octubre_30.csv')
api_call_31 = pd.read_csv('./doce_octubre/doce_octubre_31.csv')
api_call_32 = pd.read_csv('./doce_octubre/doce_octubre_32.csv')
api_call_33 = pd.read_csv('./doce_octubre/doce_octubre_33.csv')
api_call_34 = pd.read_csv('./doce_octubre/doce_octubre_34.csv')
api_call_35 = pd.read_csv('./doce_octubre/doce_octubre_35.csv')

In [37]:
api_call_1.head()

,Unnamed: 0,link,rating,date,source,review_id,snippet,likes,user.name,user.link,user.contributor_id,user.thumbnail,user.reviews,extracted_snippet.original,extracted_snippet.translated,user.photos,user.local_guide
0,0,https://www.google.com/maps/reviews/data=!4m8!...,1.0,12 hours ago,Google,ChdDSUhNMG9nS0VJQ0FnSUM5LUx1RTNRRRAB,Un avergüenza que tenga en la sala de espera m...,1.0,Ldqbena Mimun,https://www.google.com/maps/contrib/1167701728...,116770172894550245384,https://lh3.googleusercontent.com/a/ACg8ocLQcA...,1.0,Un avergüenza que tenga en la sala de espera m...,It's a shame that I have been in the waiting r...,NaN,NaN
1,1,https://www.google.com/maps/reviews/data=!4m8!...,5.0,a day ago,Google,ChZDSUhNMG9nS0VJQ0FnSUM5cUpqVFZREAE,"Buen trato, nuevas instalaciones y lo último e...",NaN,Lucas Blanco,https://www.google.com/maps/contrib/1130265625...,113026562595316099853,https://lh3.googleusercontent.com/a-/ALV-UjV1v...,68.0,"Buen trato, nuevas instalaciones y lo último e...","Good treatment, new facilities and the latest ...",11.0,NaN
2,2,https://www.google.com/maps/reviews/data=!4m8!...,5.0,2 days ago,Google,ChdDSUhNMG9nS0VJQ0FnSURkMzZpZHNRRRAB,NaN,NaN,MRocio M V,https://www.google.com/maps/contrib/1130155364...,113015536431992903762,https://lh3.googleusercontent.com/a-/ALV-UjXrS...,10.0,NaN,NaN,6.0,True
3,3,https://www.google.com/maps/reviews/data=!4m8!...,4.0,2 days ago,Google,ChZDSUhNMG9nS0VJQ0FnSURkOTZXMFBnEAE,NaN,NaN,Angel de Arce,https://www.google.com/maps/contrib/1020326022...,102032602225573880769,https://lh3.googleusercontent.com/a-/ALV-UjWP1...,122.0,NaN,NaN,NaN,NaN
4,4,https://www.google.com/maps/reviews/data=!4m8!...,1.0,2 days ago,Google,ChZDSUhNMG9nS0VJQ0FnSURkOThDTFpnEAE,NaN,NaN,Lidia Yarza,https://www.google.com/maps/contrib/1057128667...,105712866780666146034,https://lh3.googleusercontent.com/a/ACg8ocKrGi...,NaN,NaN,NaN,NaN,NaN

In [5]:
if api_call_1['snippet'].equals(api_call_1['extracted_snippet.original']):
    print('Es igual')
else:
    print('Hay algo distinto')

Es igual

## 1. Concat

In [6]:
len(api_call_10)

10

In [38]:
df_doce_octubre = pd.concat([api_call_1,
                            api_call_2,
                            api_call_3,
                            api_call_4,
                            api_call_5,
                            api_call_6,
                            api_call_7,
                            api_call_8,
                            api_call_9,
                            api_call_10,
                            api_call_11,
                            api_call_12,
                            api_call_13,
                            api_call_14,
                            api_call_15,
                            api_call_16,
                            api_call_17,
                            api_call_18,
                            api_call_19,
                            api_call_20,
                            api_call_21,
                            api_call_22,
                            api_call_23,
                            api_call_24,
                            api_call_25,
                            api_call_26,
                            api_call_27,
                            api_call_28,
                            api_call_29,
                            api_call_30,
                            api_call_31,
                            api_call_32,
                            api_call_33,
                            api_call_34,
                            api_call_35,
                            ], sort=False, ignore_index=True)

In [39]:
df_doce_octubre

,Unnamed: 0,link,rating,date,source,review_id,snippet,likes,user.name,user.link,...,user.reviews,extracted_snippet.original,extracted_snippet.translated,user.photos,user.local_guide,images,details.un_consejo_para_elena,details.pd,details.estoy_citada_para_la_tercera_dosis_y_he_llegado_a_las_2,details.es_evidente_que_nos_cobran_de_nuestro_trabajo_y_esfuerzo_para_pagar_el_sueldo_de_estos_enfermeros_y_doctores_y_estos_aun_así_no_tienen_la_honorabilidad_de_atendernos_como_personas_y_más_en_situación_de_urgencia_como_toda_la_gente_que_ha_día_y_hora_de_hoy_22_03_2023_22
0,0,https://www.google.com/maps/reviews/data=!4m8!...,1.0,12 hours ago,Google,ChdDSUhNMG9nS0VJQ0FnSUM5LUx1RTNRRRAB,Un avergüenza que tenga en la sala de espera m...,1.0,Ldqbena Mimun,https://www.google.com/maps/contrib/1167701728...,...,1.0,Un avergüenza que tenga en la sala de espera m...,It's a shame that I have been in the waiting r...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,https://www.google.com/maps/reviews/data=!4m8!...,5.0,a day ago,Google,ChZDSUhNMG9nS0VJQ0FnSUM5cUpqVFZREAE,"Buen trato, nuevas instalaciones y lo último e...",NaN,Lucas Blanco,https://www.google.com/maps/contrib/1130265625...,...,68.0,"Buen trato, nuevas instalaciones y lo último e...","Good treatment, new facilities and the latest ...",11.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2,https://www.google.com/maps/reviews/data=!4m8!...,5.0,2 days ago,Google,ChdDSUhNMG9nS0VJQ0FnSURkMzZpZHNRRRAB,NaN,NaN,MRocio M V,https://www.google.com/maps/contrib/1130155364...,...,10.0,NaN,NaN,6.0,True,NaN,NaN,NaN,NaN,NaN
3,3,https://www.google.com/maps/reviews/data=!4m8!...,4.0,2 days ago,Google,ChZDSUhNMG9nS0VJQ0FnSURkOTZXMFBnEAE,NaN,NaN,Angel de Arce,https://www.google.com/maps/contrib/1020326022...,...,122.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,https://www.google.com/maps/reviews/data=!4m8!...,1.0,2 days ago,Google,ChZDSUhNMG9nS0VJQ0FnSURkOThDTFpnEAE,NaN,NaN,Lidia Yarza,https://www.google.com/maps/contrib/1057128667...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,5,https://www.google.com/maps/reviews/data=!4m8!...,5.0,a year ago,Google,ChdDSUhNMG9nS0VJQ0FnSURod29tQnJRRRAB,NaN,NaN,Laura Garcia,https://www.google.com/maps/contrib/1008245257...,...,142.0,NaN,NaN,20.0,True,NaN,NaN,NaN,NaN,NaN
346,6,https://www.google.com/maps/reviews/data=!4m8!...,5.0,a year ago,Google,ChdDSUhNMG9nS0VJQ0FnSURoblBlcHJBRRAB,"Todas las veces que necesitado ir allí, SIEMPR...",3.0,Rayanne Rodrigues Da Silva,https://www.google.com/maps/contrib/1015817763...,...,26.0,"Todas las veces que necesitado ir allí, SIEMPR...","Every time I needed to go there, ALWAYS, they ...",16.0,True,NaN,NaN,NaN,NaN,NaN
347,7,https://www.google.com/maps/reviews/data=!4m8!...,4.0,a year ago,Google,ChZDSUhNMG9nS0VJQ0FnSURobVBMeVh3EAE,Muy contento con los profesionales...se que se...,1.0,Israel Villacis C.,https://www.google.com/maps/contrib/1017662779...,...,8.0,Muy contento con los profesionales...se que se...,Very happy with the professionals...I know tha...,2.0,NaN,NaN,NaN,NaN,NaN,NaN
348,8,https://www.google.com/maps/reviews/data=!4m8!...,1.0,a year ago,Google,ChdDSUhNMG9nS0VJQ0FnSURod1AzbHB3RRAB,Lo peor más de 7 horas y aún nada que lo atien...,NaN,Jhon Edinson Garzon Rubio,https://www.google.com/maps/contrib/1171982457...,...,2.0,Lo peor más de 7 horas y aún nada que lo atien...,The worst thing is more than 7 hours and still...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
349,9,https://www.google.com/maps/reviews/data=!4m8!...,1.0,a year ago,Google,ChdDSUhNMG9nS0VJQ0FnSURod0xUbThnRRAB,Fatal madre mia todos salen a tomar algo fuera...,NaN,Luciajunior Celi Rojas,https://www.google.com/maps/contrib/1053459812...,...,4.0,Fatal madre mia todos salen a tomar algo fuera...,"My god, everyone goes out to have a drink and ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
df_doce_octubre.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 22 columns):
 #   Column                                                                                                                                                                                                                                                                                Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                                                                --------------  -----
 0   Unnamed: 0                                                                                                                                                                                                                                                                            350 non-null    int64
 1   link                                                                                                                                                                                                                                                                                  350 non-null    object
 2   rating                                                                                                                                                                                                                                                                                350 non-null    float64
 3   date                                                                                                                                                                                                                                                                                  350 non-null    object
 4   source                                                                                                                                                                                                                                                                                350 non-null    object
 5   review_id                                                                                                                                                                                                                                                                             350 non-null    object
 6   snippet                                                                                                                                                                                                                                                                               263 non-null    object
 7   likes                                                                                                                                                                                                                                                                                 150 non-null    float64
 8   user.name                                                                                                                                                                                                                                                                             350 non-null    object
 9   user.link                                                                                                                                                                                                                                                                             350 non-null    object
 10  user.contributor_id                                                                                                                                                                                                                                                                   350 non-null    object
 11  user.thumbnail                                                                                                                                                                                                                                                                        350 non-null    object
 12  user.reviews                                                                                                                                                                                                                                                                          343 non-null    float64
 13  extracted_snippet.original                                                                                                                                                                                                                                                            259 non-null    object
 14  extracted_snippet.translated                                                                                                                                                                                                                                                          259 non-null    object
 15  user.photos                                                                                                                                                                                                                                                                           196 non-null    float64
 16  user.local_guide                                                                                                                                                                                                                                                                      151 non-null    object
 17  images                                                                                                                                                                                                                                                                                8 non-null      object
 18  details.un_consejo_para_elena                                                                                                                                                                                                                                                         1 non-null      object
 19  details.pd                                                                                                                                                                                                                                                                            1 non-null      object
 20  details.estoy_citada_para_la_tercera_dosis_y_he_llegado_a_las_2                                                                                                                                                                                                                       1 non-null      object
 21  details.es_evidente_que_nos_cobran_de_nuestro_trabajo_y_esfuerzo_para_pagar_el_sueldo_de_estos_enfermeros_y_doctores_y_estos_aun_así_no_tienen_la_honorabilidad_de_atendernos_como_personas_y_más_en_situación_de_urgencia_como_toda_la_gente_que_ha_día_y_hora_de_hoy_22_03_2023_22  1 non-null      object
dtypes: float64(4), int64(1), object(17)
memory usage: 60.3+ KB

In [12]:
df_doce_octubre.head(40)

,Unnamed: 0,link,rating,date,source,review_id,snippet,likes,user.name,user.link,...,user.reviews,extracted_snippet.original,extracted_snippet.translated,user.photos,user.local_guide,images,details.un_consejo_para_elena,details.pd,details.estoy_citada_para_la_tercera_dosis_y_he_llegado_a_las_2,details.es_evidente_que_nos_cobran_de_nuestro_trabajo_y_esfuerzo_para_pagar_el_sueldo_de_estos_enfermeros_y_doctores_y_estos_aun_así_no_tienen_la_honorabilidad_de_atendernos_como_personas_y_más_en_situación_de_urgencia_como_toda_la_gente_que_ha_día_y_hora_de_hoy_22_03_2023_22
0,0,https://www.google.com/maps/reviews/data=!4m8!...,1.0,12 hours ago,Google,ChdDSUhNMG9nS0VJQ0FnSUM5LUx1RTNRRRAB,Un avergüenza que tenga en la sala de espera m...,1.0,Ldqbena Mimun,https://www.google.com/maps/contrib/1167701728...,...,1.0,Un avergüenza que tenga en la sala de espera m...,It's a shame that I have been in the waiting r...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,https://www.google.com/maps/reviews/data=!4m8!...,5.0,a day ago,Google,ChZDSUhNMG9nS0VJQ0FnSUM5cUpqVFZREAE,"Buen trato, nuevas instalaciones y lo último e...",NaN,Lucas Blanco,https://www.google.com/maps/contrib/1130265625...,...,68.0,"Buen trato, nuevas instalaciones y lo último e...","Good treatment, new facilities and the latest ...",11.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2,https://www.google.com/maps/reviews/data=!4m8!...,5.0,2 days ago,Google,ChdDSUhNMG9nS0VJQ0FnSURkMzZpZHNRRRAB,NaN,NaN,MRocio M V,https://www.google.com/maps/contrib/1130155364...,...,10.0,NaN,NaN,6.0,True,NaN,NaN,NaN,NaN,NaN
3,3,https://www.google.com/maps/reviews/data=!4m8!...,4.0,2 days ago,Google,ChZDSUhNMG9nS0VJQ0FnSURkOTZXMFBnEAE,NaN,NaN,Angel de Arce,https://www.google.com/maps/contrib/1020326022...,...,122.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,https://www.google.com/maps/reviews/data=!4m8!...,1.0,2 days ago,Google,ChZDSUhNMG9nS0VJQ0FnSURkOThDTFpnEAE,NaN,NaN,Lidia Yarza,https://www.google.com/maps/contrib/1057128667...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,https://www.google.com/maps/reviews/data=!4m8!...,5.0,4 days ago,Google,ChdDSUhNMG9nS0VJQ0FnSURkNDl1Unh3RRAB,"Están atendiendo a mi padre y enfermeras, auxi...",NaN,José Ignacio Ibáñez,https://www.google.com/maps/contrib/1054917974...,...,137.0,"Están atendiendo a mi padre y enfermeras, auxi...","They are caring for my father and the nurses, ...",2.0,True,NaN,NaN,NaN,NaN,NaN
6,6,https://www.google.com/maps/reviews/data=!4m8!...,1.0,6 days ago,Google,ChdDSUhNMG9nS0VJQ0FnSURkNFlybTZ3RRAB,Llevamos 3 años en manos del supuesto jefe de ...,NaN,Alicia Hernando,https://www.google.com/maps/contrib/1069845763...,...,14.0,Llevamos 3 años en manos del supuesto jefe de ...,We have been in the hands of the supposed head...,10.0,True,NaN,NaN,NaN,NaN,NaN
7,7,https://www.google.com/maps/reviews/data=!4m8!...,4.0,a week ago,Google,ChdDSUhNMG9nS0VJQ0FnSURkb2R6X3RBRRAB,NaN,NaN,Mildre Edith Torres Cardenas,https://www.google.com/maps/contrib/1058149097...,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8,https://www.google.com/maps/reviews/data=!4m8!...,1.0,a week ago,Google,ChdDSUhNMG9nS0VJQ0FnSURkdW8ycG13RRAB,"Neurología pésima atención ,poca ilusión .Ning...",NaN,Ana Alb,https://www.google.com/maps/contrib/1010611265...,...,35.0,"Neurología pésima atención ,poca ilusión .Ning...","Neurology, terrible attention, little enthusia...",1.0,True,NaN,NaN,NaN,NaN,NaN
9,9,https://www.google.com/maps/reviews/data=!4m8!...,5.0,a week ago,Google,ChZDSUhNMG9nS0VJQ0FnSURkbXR5TUtBEAE,Uno de los mejores hospitales de Madrid,NaN,Miguel Angel Cano,https://www.google.com/maps/contrib/1016297384...,...,2.0,Uno de los mejores hospitales de Madrid,One of the best hospitals in Madrid,1.0,NaN,NaN,NaN,NaN,NaN,NaN
10,0,https://www.google.com/maps/reviews/data=!4m8!...,1.0,a week ago,Google,ChdDSUhNMG9nS0VJQ0FnSURkOG9QczNBRRAB,Si aparcamiento para urgencias te tienes que b...,NaN,freak show,https://www.google.com/maps/contrib/1114804504...,...,108.0,Si aparcamiento para urgencias te tienes que b...,If you park for emergencies you have to make a...,10.0,True,NaN,NaN,NaN,NaN,NaN
11,1,https://www.google.com/maps/reviews/data=!4m8!...,1.0,a week ago,Google,ChdDSUhNMG9nS0VJQ0FnSURkek02czRBRRAB,El peor hospital que he ido de largo. Pasotism...,NaN,FERNÁNDEZ VELASCO ALBERTO,https://www.google.com/maps/contrib/1152469475...,...,11.0,El peor hospital que he ido de largo. Pasotism...,The worst hospital I have ever been to. Steple...,2.0,NaN,NaN,NaN,NaN,NaN,NaN
12,2,https://www.google.com/maps/reviews/data=!4m8!...,1.0,a week ago,Google,ChdDSUhNMG9nS0VJQ0FnSURkMU5fZnh3RRAB,Voy con una silla de ruedas ya hay 8 aparcamie...,NaN,FLEKI,https://www.google.com/maps/contrib/1035584824...,...,126.0,Voy con una silla de ruedas ya hay 8 aparcamie...,I go with a wheelchair. There are already 8 pa...,151.0,True,NaN,NaN,NaN,NaN,NaN
13,3,https://www.google.com/maps/reviews/data=!4m8!...,1.0,2 weeks ago,Google,ChdDSUhNMG9nS0VJQ0FnSUNkNWQ2dmhBRRAB,Estoy totalmente disgustada con un cirujano de...,2.0,Nadia Atienza,https://www.google.com/maps/contrib/1044418214...,...,18.0,Estoy totalmente disgustada con un cirujano de...,I am totally disgusted with an SS surgeon at t...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,4,https://www.google.com/maps/reviews/data=!4m8!...,3.0,2 weeks ago,Google,ChdDSUhNMG9nS0VJQ0FnSUNkbWVqMHh3RRAB,NaN,NaN,josse luis,https://www.google.com/maps/contrib/1091107676...,...,16.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN
15,5,https://www.google.com/maps/reviews/data=!4m8!...,5.0,2 weeks ago,Google,ChZDSUhNMG9nS0VJQ0FnSUNka2RuUU93EAE,"Mi abuela de 93 años, entró muy grave y gracia...",NaN,vanessa moreno escaño,https://www.google.com/maps/contrib/1136757596...,...,30.0,"Mi abuela de 93 años, entró muy grave y gracia...",My 93-year-old grandmother was seriously ill a...,11.0,NaN,NaN,NaN,NaN,NaN,NaN
16,6,https://www.google.com/maps/reviews/data=!4m8!...,5.0,2 weeks ago,Google,ChZDSUhNMG9nS0VJQ0FnSUNkd2FlWkVREAE,NaN,NaN,Raúl Esteban,https://www.google.com/maps/contrib/1160904795...,...,28.0,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN
17,7,https://www.google.com/maps/reviews/data=!4m8!...,5.0,2 weeks ago,Google,ChdDSUhNMG9nS0VJQ0FnSUNkaE0zanJnRRAB,NaN,NaN,Miguel,https://www.google.com/maps/contrib/1003480107...,...,84.0,NaN,NaN,15.0,True,NaN,NaN,NaN,NaN,NaN
18,8,https://www.google.com/maps/reviews/data=!4m8!...,1.0,2 weeks ago,Google,ChdDSUhNMG9nS0VJQ0FnSUNkMk5fcDFnRRAB,"Hospital tercermundista,se cae a trozos y nadi...",NaN,Monica Garcia,https://www.google.com/maps/contrib/1018432333...,...,22.0,"Hospital tercermundista,se cae a trozos y nadi...","Third world hospital, it is falling apart and ...",11.0,NaN,NaN,NaN,NaN,NaN,NaN
19,9,https://www.google.com/maps/reviews/data=!4m8!...,1.0,2 weeks ago,Google,ChZDSUhNMG9nS0VJQ0FnSUNkcU1LQ1ZBEAE,Mi hija acaba de cumplir 16 años y por desgrac...,NaN,marisa glez,https://www.google.com/maps/contrib/1026426881...,...,7.0,Mi hija acaba de cumplir 16 años y por desgrac...,My daughter has just turned 16 and unfortunate...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,0,https://www.google.com/maps/reviews/data=!4m8!...,1.0,2 weeks ago,Google,ChdDSUhNMG9nS0VJQ0FnSUNkNWQ2dmhBRRAB,Estoy totalmente disgustada con un cirujano de...,3.0,Nadia Atienza,https://www.google.com/maps/contrib/1044418214...,...,18.0,Estoy totalmente disgustada con un cirujano de...,I am totally disgusted with an SS surgeon at t...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,1,https://www.google.com/maps/reviews/data=!4m8!...,3.0,2 weeks ago,Google,ChdDSUhNMG9nS0VJQ0FnSUNkbWVqMHh3RRAB,NaN,NaN,josse luis,https://www.google.com/maps/contrib/1091107676...,...,16.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN
22,2,https://www.google.com/maps/reviews/data=!4m8!...,5.0,2 weeks ago,Google,ChZDSUhNMG9nS0VJQ0FnSUNka2RuUU93EAE,"Mi abuela de 93 años, entró muy grave y gracia...",NaN,vanessa moreno escaño,https://www.google.com/maps/contrib/1136757596...,...,30.0,"Mi abuela de 93 años, entró muy grave y gracia...",My 93-year-old grandmother was seriously ill a...,11.0,NaN,NaN,NaN,NaN,NaN,NaN
23,3,https://www.google.com/maps/reviews/data=!4m8!...,5.0,2 weeks ago,Google,ChZDSUhNMG9nS0VJQ0FnSUNkd2FlWkVREAE,NaN,NaN,Raúl Esteban,https://www.google.com/maps/contrib/1160904795...,...,28.0,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN
24,4,https://www.google.com/maps/reviews/data=!4m8!...,5.0,3 weeks ago,Google,ChdDSUhNMG9nS0VJQ0FnSUNkaE0zanJnRRAB,NaN,NaN,Miguel,https://www.google.com/maps/contrib/1003480107...,...,84.0,NaN,NaN,15.0,True,NaN,NaN,NaN,NaN,NaN
25,5,https://www.google.com/maps/reviews/data=!4m8!...,1.0,3 weeks ago,Google,ChdDSUhNMG9nS0VJQ0FnSUNkMk5fcDFnRRAB,"Hospital tercermundista,se cae a trozos y nadi...",NaN,Monica Garcia,https://www.google.com/maps/contrib/1018432333...,...,22.0,"Hospital tercermundista,se cae a trozos y nadi...","Third world hospital, it is falling apart and ...",11.0,NaN,NaN,NaN,NaN,NaN,NaN
26,6,https://www.google.com/maps/reviews/data=!4m8!...,1.0,3 weeks ago,Google,ChZDSUhNMG9nS0VJQ0FnSUNkcU1LQ1ZBEAE,Mi hija acaba de cumplir 16 años y por desgrac...,1.0,marisa glez,https://www.google.com/maps/contrib/1026426881...,...,7.0,Mi hija acaba de cumplir 16 años y por desgrac...,My daughter has just turned 16 and unfortunate...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,7,https://www.google.com/maps/reviews/data=!4m8!...,5.0,3 weeks ago,Google,ChZDSUhNMG9nS0VJQ0FnSUNkOE5PSEp3EAE,NaN,NaN,Romaneremii Єремій,https://www.google.com/maps/contrib/1132357432...,...,58.0,NaN,NaN,5.0,True,NaN,NaN,NaN,NaN,NaN
28,8,https://www.google.com/maps/reviews/data=!4m8!...,2.0,3 weeks ago,Google,ChZDSUhNMG9nS0VJQ0FnSUNka0kySE9nEAE,"Hospital viejo, con instalaciones muy deterior...",NaN,maria Capa,https://www.google.com/maps/contrib/1150730825...,...,132.0,"Hospital viejo, con instalaciones muy deterior...","Old hospital, with very deteriorated facilitie...",2.0,NaN,NaN,NaN,NaN,NaN,NaN
29,9,https://www.google.com/maps/reviews/data=!4m8!...,1.0,3 weeks ago,Google,ChZDSUhNMG9nS0VJQ0FnSUNka083WmFBEAE,"Verdaderamente es una vergüenza, he llegado al...",NaN,Vanesanzang Edumurugui,https://www.google.com/maps/contrib/1049971433...,...,1.0,"Verdaderamente es una vergüenza, he llegado al...","It is truly a shame, I arrived at the hospital...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,0,https://www.google.com/maps/reviews/data=!4m8!...,3.0,3 weeks ago,Google,ChZDSUhNMG9nS0VJQ0FnSUR0NzVlaUdnEAE,NaN,NaN,juan jose perez diez,https://www.google.com/maps/contrib/1063273879...,...,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,1,https://www.google.com/maps/reviews/data=!4m8!...,5.0,3 weeks ago,Google,ChZDSUhNMG9nS0VJQ0FnSUR0dDZtUktnEAE,NaN,NaN,Africa Fdez Palacios,https://www.google.com/maps/contrib/1013933702...,...,458.0,NaN,NaN,121.0,True,NaN,NaN,NaN,NaN,NaN
32,2,https://www.google.com/maps/reviews/data=!4m8!...,5.0,3 weeks ago,Google,ChdDSUhNMG9nS0VJQ0FnSUR0LS1uVm1BRRAB,NaN,NaN,Ram Baral,https://www.google.com/maps/contrib/1089386640...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,3,https://www.google.com/maps/reviews/data=!4m8!...,5.0,4 weeks ago,Google,ChZDSUhNMG9nS0VJQ0FnSUR0eloyWUl3EAE,Buena atención desde el principio hasta el final,NaN,David Arias,https://www.google.com/maps/contrib/1083061759...,...,30.0,Buena atención desde el principio hasta el final,Good service from start to finish,13.0,True,NaN,NaN,NaN,NaN,NaN
34,4,https://www.google.com/maps/reviews/data=!4m8!...,2.0,4 weeks ago,Google,ChdDSUhNMG9nS0VJQ0FnSUR0eFl2d2lnRRAB,Puedes estar llamando todas las mañanas durant...,NaN,Noventa1 Jara1,https://www.google.com/maps/contrib/1044884138...,...,6.0,Puedes estar llamando todas las mañanas durant...,You can be calling every morning for a week wh...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,5,https://www.google.com/maps/reviews/data=!4m8!...,3.0,a month ago,Google,ChdDSUhNMG9nS0VJQ0FnSUR0M3BDYnZnRRAB,NaN,NaN,Esperanza “Espe” Fernández,https://www.google.com/maps/contrib/1038215685...,...,411.0,NaN,NaN,826.0,True,NaN,NaN,NaN,NaN,NaN
36,6,https://www.google.com/maps/reviews/data=!4m8!...,1.0,a month ago,Google,ChdDSUhNMG9nS0VJQ0FnSUR0cHBuRXBRRRAB,Fui a urgencias y diagnosticaron a mi cuñada c...,2.0,Pierandrea Amichevole,https://www.google.com/maps/contrib/1070024265...,...,19.0,Fui a urgencias y diagnosticaron a mi cuñada c...,I went to the emergency room and they diagnose...,5.0,NaN,NaN,NaN,NaN,NaN,NaN
37,7,https://www.google.com/maps/reviews/data=!4m8!...,5.0,a month ago,Google,ChZDSUhNMG9nS0VJQ0FnSUR0cW9YVVhBEAE,Buena atención a muy agradecido con los ciruja...,NaN,Yeiner alexander Carmona,https://www.google.com/maps/contrib/1153599439...,...,7.0,Buena atención a muy agradecido con los ciruja...,"Good care, very grateful to the surgeons, nurs...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,8,https://www.google.com/maps/reviews/data=!4m8!...,5.0,a month ago,Google,ChZDSUhNMG9nS0VJQ0FnSUR0cUpIWFZ3EAE,NaN,NaN,Cesáreo Del Burgo Álvarez,https://www.google.com/maps/contrib/1162522612...,...,24.0,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN
39,9,https://www.google.com/maps/reviews/data=!4m8!...,5.0,a month ago,Google,ChZDSUhNMG9nS0VJQ0FnSUR0eU1xVElnEAE,NaN,NaN,Javier Morago,https://www.google.com/maps/contrib/1147171915...,...,137.0,NaN,NaN,28.0,True,NaN,NaN,NaN,NaN,NaN

In [41]:
df_doce_octubre = df_doce_octubre.drop_duplicates(subset=['link'])

In [42]:
df_doce_octubre

,Unnamed: 0,link,rating,date,source,review_id,snippet,likes,user.name,user.link,...,user.reviews,extracted_snippet.original,extracted_snippet.translated,user.photos,user.local_guide,images,details.un_consejo_para_elena,details.pd,details.estoy_citada_para_la_tercera_dosis_y_he_llegado_a_las_2,details.es_evidente_que_nos_cobran_de_nuestro_trabajo_y_esfuerzo_para_pagar_el_sueldo_de_estos_enfermeros_y_doctores_y_estos_aun_así_no_tienen_la_honorabilidad_de_atendernos_como_personas_y_más_en_situación_de_urgencia_como_toda_la_gente_que_ha_día_y_hora_de_hoy_22_03_2023_22
0,0,https://www.google.com/maps/reviews/data=!4m8!...,1.0,12 hours ago,Google,ChdDSUhNMG9nS0VJQ0FnSUM5LUx1RTNRRRAB,Un avergüenza que tenga en la sala de espera m...,1.0,Ldqbena Mimun,https://www.google.com/maps/contrib/1167701728...,...,1.0,Un avergüenza que tenga en la sala de espera m...,It's a shame that I have been in the waiting r...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,https://www.google.com/maps/reviews/data=!4m8!...,5.0,a day ago,Google,ChZDSUhNMG9nS0VJQ0FnSUM5cUpqVFZREAE,"Buen trato, nuevas instalaciones y lo último e...",NaN,Lucas Blanco,https://www.google.com/maps/contrib/1130265625...,...,68.0,"Buen trato, nuevas instalaciones y lo último e...","Good treatment, new facilities and the latest ...",11.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2,https://www.google.com/maps/reviews/data=!4m8!...,5.0,2 days ago,Google,ChdDSUhNMG9nS0VJQ0FnSURkMzZpZHNRRRAB,NaN,NaN,MRocio M V,https://www.google.com/maps/contrib/1130155364...,...,10.0,NaN,NaN,6.0,True,NaN,NaN,NaN,NaN,NaN
3,3,https://www.google.com/maps/reviews/data=!4m8!...,4.0,2 days ago,Google,ChZDSUhNMG9nS0VJQ0FnSURkOTZXMFBnEAE,NaN,NaN,Angel de Arce,https://www.google.com/maps/contrib/1020326022...,...,122.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,https://www.google.com/maps/reviews/data=!4m8!...,1.0,2 days ago,Google,ChZDSUhNMG9nS0VJQ0FnSURkOThDTFpnEAE,NaN,NaN,Lidia Yarza,https://www.google.com/maps/contrib/1057128667...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,5,https://www.google.com/maps/reviews/data=!4m8!...,5.0,a year ago,Google,ChdDSUhNMG9nS0VJQ0FnSURod29tQnJRRRAB,NaN,NaN,Laura Garcia,https://www.google.com/maps/contrib/1008245257...,...,142.0,NaN,NaN,20.0,True,NaN,NaN,NaN,NaN,NaN
346,6,https://www.google.com/maps/reviews/data=!4m8!...,5.0,a year ago,Google,ChdDSUhNMG9nS0VJQ0FnSURoblBlcHJBRRAB,"Todas las veces que necesitado ir allí, SIEMPR...",3.0,Rayanne Rodrigues Da Silva,https://www.google.com/maps/contrib/1015817763...,...,26.0,"Todas las veces que necesitado ir allí, SIEMPR...","Every time I needed to go there, ALWAYS, they ...",16.0,True,NaN,NaN,NaN,NaN,NaN
347,7,https://www.google.com/maps/reviews/data=!4m8!...,4.0,a year ago,Google,ChZDSUhNMG9nS0VJQ0FnSURobVBMeVh3EAE,Muy contento con los profesionales...se que se...,1.0,Israel Villacis C.,https://www.google.com/maps/contrib/1017662779...,...,8.0,Muy contento con los profesionales...se que se...,Very happy with the professionals...I know tha...,2.0,NaN,NaN,NaN,NaN,NaN,NaN
348,8,https://www.google.com/maps/reviews/data=!4m8!...,1.0,a year ago,Google,ChdDSUhNMG9nS0VJQ0FnSURod1AzbHB3RRAB,Lo peor más de 7 horas y aún nada que lo atien...,NaN,Jhon Edinson Garzon Rubio,https://www.google.com/maps/contrib/1171982457...,...,2.0,Lo peor más de 7 horas y aún nada que lo atien...,The worst thing is more than 7 hours and still...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
349,9,https://www.google.com/maps/reviews/data=!4m8!...,1.0,a year ago,Google,ChdDSUhNMG9nS0VJQ0FnSURod0xUbThnRRAB,Fatal madre mia todos salen a tomar algo fuera...,NaN,Luciajunior Celi Rojas,https://www.google.com/maps/contrib/1053459812...,...,4.0,Fatal madre mia todos salen a tomar algo fuera...,"My god, everyone goes out to have a drink and ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 2. Drop columns

In [43]:
df_doce_octubre.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 343 entries, 0 to 349
Data columns (total 22 columns):
 #   Column                                                                                                                                                                                                                                                                                Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                                                                --------------  -----
 0   Unnamed: 0                                                                                                                                                                                                                                                                            343 non-null    int64
 1   link                                                                                                                                                                                                                                                                                  343 non-null    object
 2   rating                                                                                                                                                                                                                                                                                343 non-null    float64
 3   date                                                                                                                                                                                                                                                                                  343 non-null    object
 4   source                                                                                                                                                                                                                                                                                343 non-null    object
 5   review_id                                                                                                                                                                                                                                                                             343 non-null    object
 6   snippet                                                                                                                                                                                                                                                                               259 non-null    object
 7   likes                                                                                                                                                                                                                                                                                 148 non-null    float64
 8   user.name                                                                                                                                                                                                                                                                             343 non-null    object
 9   user.link                                                                                                                                                                                                                                                                             343 non-null    object
 10  user.contributor_id                                                                                                                                                                                                                                                                   343 non-null    object
 11  user.thumbnail                                                                                                                                                                                                                                                                        343 non-null    object
 12  user.reviews                                                                                                                                                                                                                                                                          336 non-null    float64
 13  extracted_snippet.original                                                                                                                                                                                                                                                            255 non-null    object
 14  extracted_snippet.translated                                                                                                                                                                                                                                                          255 non-null    object
 15  user.photos                                                                                                                                                                                                                                                                           192 non-null    float64
 16  user.local_guide                                                                                                                                                                                                                                                                      149 non-null    object
 17  images                                                                                                                                                                                                                                                                                8 non-null      object
 18  details.un_consejo_para_elena                                                                                                                                                                                                                                                         1 non-null      object
 19  details.pd                                                                                                                                                                                                                                                                            1 non-null      object
 20  details.estoy_citada_para_la_tercera_dosis_y_he_llegado_a_las_2                                                                                                                                                                                                                       1 non-null      object
 21  details.es_evidente_que_nos_cobran_de_nuestro_trabajo_y_esfuerzo_para_pagar_el_sueldo_de_estos_enfermeros_y_doctores_y_estos_aun_así_no_tienen_la_honorabilidad_de_atendernos_como_personas_y_más_en_situación_de_urgencia_como_toda_la_gente_que_ha_día_y_hora_de_hoy_22_03_2023_22  1 non-null      object
dtypes: float64(4), int64(1), object(17)
memory usage: 61.6+ KB

In [44]:
drop_cols = ['Unnamed: 0',
             'link',
            'source',
            'review_id',
            'user.name',
            'user.link',
            'user.contributor_id',
            'user.thumbnail',
            'user.reviews',
            'extracted_snippet.original',
            'extracted_snippet.translated', 
            'images',
            'user.photos',
             #'response.date',
             #'response.snippet',
            #'response.extracted_snippet.original', 
            #'response.extracted_snippet.translated',
            'likes',
            'user.local_guide',
            'details.un_consejo_para_elena',
            'details.pd',
            'details.estoy_citada_para_la_tercera_dosis_y_he_llegado_a_las_2',
            'details.es_evidente_que_nos_cobran_de_nuestro_trabajo_y_esfuerzo_para_pagar_el_sueldo_de_estos_enfermeros_y_doctores_y_estos_aun_así_no_tienen_la_honorabilidad_de_atendernos_como_personas_y_más_en_situación_de_urgencia_como_toda_la_gente_que_ha_día_y_hora_de_hoy_22_03_2023_22']

In [45]:
df_doce_octubre = df_doce_octubre.drop(columns=[columna for columna in drop_cols if columna in df_doce_octubre.columns], errors='ignore')
print(f'Eliminadas las columnas innecesarias del DataFrame. Ahora cuenta con las siguientes columnas: ', len(df_doce_octubre.columns))

Eliminadas las columnas innecesarias del DataFrame. Ahora cuenta con las siguientes columnas:  3

In [46]:
df_doce_octubre.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 343 entries, 0 to 349
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   rating   343 non-null    float64
 1   date     343 non-null    object
 2   snippet  259 non-null    object
dtypes: float64(1), object(2)
memory usage: 10.7+ KB

## 3. Corrección en date

In [47]:
df_doce_octubre['date'].value_counts()

2 months ago     41
8 months ago     35
5 months ago     34
10 months ago    31
11 months ago    30
a month ago      30
4 months ago     27
3 months ago     27
6 months ago     21
9 months ago     19
7 months ago     14
2 weeks ago       7
a year ago        6
3 weeks ago       6
a week ago        6
2 days ago        3
4 weeks ago       2
a day ago         1
6 days ago        1
4 days ago        1
12 hours ago      1
Name: date, dtype: int64

In [52]:
fechas = {
    '12 hours ago': '2024-02-01',
    'a day ago': '2024-02-01',
    '4 days ago': '2024-02-01',
    '6 days ago': '2024-02-01',
    '2 days ago': '2024-02-01',
    'a week ago': '2024-02-01',
    '2 weeks ago': '2024-02-01',
    '3 weeks ago': '2024-02-01',
    '4 weeks ago': '2024-02-01',
    'a month ago': '2024-01-01',
    '2 months ago': '2023-12-01',
    '3 months ago': '2023-11-01',
    '4 months ago': '2023-10-01',
    '5 months ago': '2023-09-01',
    '6 months ago': '2023-08-01',
    '7 months ago': '2023-07-01',
    '8 months ago': '2023-06-01',
    '9 months ago': '2023-05-01',
    '10 months ago': '2023-04-01',
    '11 months ago': '2023-03-01',
    'a year ago': 'eliminar'
}

In [53]:
df_doce_octubre['Fecha'] = df_doce_octubre['date'].map(fechas).fillna(pd.to_datetime(df_doce_octubre['date'], errors='coerce'))

In [54]:
df_doce_octubre.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 343 entries, 0 to 349
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   rating   343 non-null    float64
 1   date     343 non-null    object
 2   snippet  259 non-null    object
 3   Fecha    343 non-null    object
dtypes: float64(1), object(3)
memory usage: 13.4+ KB

In [55]:
filas_nulas = df_doce_octubre[df_doce_octubre['Fecha'].isnull()]
print(filas_nulas)

Empty DataFrame
Columns: [rating, date, snippet, Fecha]
Index: []

In [57]:
df_doce_octubre = df_doce_octubre[df_doce_octubre['Fecha'] != 'eliminar']

In [58]:
df_doce_octubre.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 337 entries, 0 to 343
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   rating   337 non-null    float64
 1   date     337 non-null    object
 2   snippet  254 non-null    object
 3   Fecha    337 non-null    object
dtypes: float64(1), object(3)
memory usage: 13.2+ KB

In [59]:
df_doce_octubre.tail()

,rating,date,snippet,Fecha
339,1.0,11 months ago,Esperas interminables y mucha falta de profesi...,2023-03-01
340,5.0,11 months ago,Fui a urgencias por que se me cayó una señora ...,2023-03-01
341,1.0,11 months ago,"Una vergüenza de personal , les pido porfavor ...",2023-03-01
342,5.0,11 months ago,Un 10 para las enfermeras y auxiliares de la 5...,2023-03-01
343,4.0,11 months ago,NaN,2023-03-01

In [60]:
df_doce_octubre.drop('date', axis=1, inplace=True)

C:\Users\tete1\AppData\Local\Temp\ipykernel_2712\1947918866.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_doce_octubre.drop('date', axis=1, inplace=True)

In [61]:
df_doce_octubre.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 337 entries, 0 to 343
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   rating   337 non-null    float64
 1   snippet  254 non-null    object
 2   Fecha    337 non-null    object
dtypes: float64(1), object(2)
memory usage: 10.5+ KB

In [62]:
df_doce_octubre['Fecha'] = pd.to_datetime(df_doce_octubre['Fecha'])

C:\Users\tete1\AppData\Local\Temp\ipykernel_2712\2528205506.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_doce_octubre['Fecha'] = pd.to_datetime(df_doce_octubre['Fecha'])

In [63]:
df_doce_octubre.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 337 entries, 0 to 343
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   rating   337 non-null    float64
 1   snippet  254 non-null    object
 2   Fecha    337 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 10.5+ KB

In [64]:
df_doce_octubre.tail()

     rating                                            snippet      Fecha
339     1.0  Esperas interminables y mucha falta de profesi... 2023-03-01
340     5.0  Fui a urgencias por que se me cayó una señora ... 2023-03-01
341     1.0  Una vergüenza de personal , les pido porfavor ... 2023-03-01
342     5.0  Un 10 para las enfermeras y auxiliares de la 5... 2023-03-01
343     4.0                                                NaN 2023-03-01

## 4. Nuevas columnas: Nombre establecimiento, Ciudad y Dirección

In [66]:
df_doce_octubre = df_doce_octubre.assign(Ciudad='Madrid', Dirección='Av. de Córdoba, s/n', Establecimiento='Hospital Universitario 12 de Octubre', CP=28041)

In [67]:
df_doce_octubre.head()

,rating,snippet,Fecha,Ciudad,Dirección,Establecimiento,CP
0,1.0,Un avergüenza que tenga en la sala de espera m...,2024-02-01,Madrid,"Av. de Córdoba, s/n",Hospital Universitario 12 de Octubre,28041
1,5.0,"Buen trato, nuevas instalaciones y lo último e...",2024-02-01,Madrid,"Av. de Córdoba, s/n",Hospital Universitario 12 de Octubre,28041
2,5.0,NaN,2024-02-01,Madrid,"Av. de Córdoba, s/n",Hospital Universitario 12 de Octubre,28041
3,4.0,NaN,2024-02-01,Madrid,"Av. de Córdoba, s/n",Hospital Universitario 12 de Octubre,28041
4,1.0,NaN,2024-02-01,Madrid,"Av. de Córdoba, s/n",Hospital Universitario 12 de Octubre,28041

## 5. Cambiar el datatype de rating a int64

In [68]:
df_doce_octubre['rating'] = df_doce_octubre['rating'].astype('int64')

In [69]:
df_doce_octubre.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 337 entries, 0 to 343
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   rating           337 non-null    int64
 1   snippet          254 non-null    object
 2   Fecha            337 non-null    datetime64[ns]
 3   Ciudad           337 non-null    object
 4   Dirección        337 non-null    object
 5   Establecimiento  337 non-null    object
 6   CP               337 non-null    int64
dtypes: datetime64[ns](1), int64(2), object(4)
memory usage: 21.1+ KB

# Hosp. Univ. Clínic de Barcelona

In [70]:
api_call_1 = pd.read_csv('./clinic_barcelona/clinic_barcelona_1.csv')
api_call_2 = pd.read_csv('./clinic_barcelona/clinic_barcelona_2.csv')
api_call_3 = pd.read_csv('./clinic_barcelona/clinic_barcelona_3.csv')
api_call_4 = pd.read_csv('./clinic_barcelona/clinic_barcelona_4.csv')
api_call_5 = pd.read_csv('./clinic_barcelona/clinic_barcelona_5.csv')
api_call_6 = pd.read_csv('./clinic_barcelona/clinic_barcelona_6.csv')
api_call_7 = pd.read_csv('./clinic_barcelona/clinic_barcelona_7.csv')
api_call_8 = pd.read_csv('./clinic_barcelona/clinic_barcelona_8.csv')
api_call_9 = pd.read_csv('./clinic_barcelona/clinic_barcelona_9.csv')
api_call_10 = pd.read_csv('./clinic_barcelona/clinic_barcelona_10.csv')
api_call_11 = pd.read_csv('./clinic_barcelona/clinic_barcelona_11.csv')
api_call_12 = pd.read_csv('./clinic_barcelona/clinic_barcelona_12.csv')
api_call_13 = pd.read_csv('./clinic_barcelona/clinic_barcelona_13.csv')
api_call_14 = pd.read_csv('./clinic_barcelona/clinic_barcelona_14.csv')
api_call_15 = pd.read_csv('./clinic_barcelona/clinic_barcelona_15.csv')
api_call_16 = pd.read_csv('./clinic_barcelona/clinic_barcelona_16.csv')
api_call_17 = pd.read_csv('./clinic_barcelona/clinic_barcelona_17.csv')
api_call_18 = pd.read_csv('./clinic_barcelona/clinic_barcelona_18.csv')
api_call_19 = pd.read_csv('./clinic_barcelona/clinic_barcelona_19.csv')
api_call_20 = pd.read_csv('./clinic_barcelona/clinic_barcelona_20.csv')
api_call_21 = pd.read_csv('./clinic_barcelona/clinic_barcelona_21.csv')
api_call_22 = pd.read_csv('./clinic_barcelona/clinic_barcelona_22.csv')
api_call_23 = pd.read_csv('./clinic_barcelona/clinic_barcelona_23.csv')
api_call_24 = pd.read_csv('./clinic_barcelona/clinic_barcelona_24.csv')
api_call_25 = pd.read_csv('./clinic_barcelona/clinic_barcelona_25.csv')
api_call_26 = pd.read_csv('./clinic_barcelona/clinic_barcelona_26.csv')
api_call_27 = pd.read_csv('./clinic_barcelona/clinic_barcelona_27.csv')
api_call_28 = pd.read_csv('./clinic_barcelona/clinic_barcelona_28.csv')
api_call_29 = pd.read_csv('./clinic_barcelona/clinic_barcelona_29.csv')
api_call_30 = pd.read_csv('./clinic_barcelona/clinic_barcelona_30.csv')
api_call_31 = pd.read_csv('./clinic_barcelona/clinic_barcelona_31.csv')
api_call_32 = pd.read_csv('./clinic_barcelona/clinic_barcelona_32.csv')

In [71]:
df_clinic_bcn = pd.concat([api_call_1,
                            api_call_2,
                            api_call_3,
                            api_call_4,
                            api_call_5,
                            api_call_6,
                            api_call_7,
                            api_call_8,
                            api_call_9,
                            api_call_10,
                            api_call_11,
                            api_call_12,
                            api_call_13,
                             api_call_14,
                             api_call_15,
                             api_call_16,
                             api_call_17,
                             api_call_18,
                             api_call_19,
                             api_call_20,
                             api_call_21,
                             api_call_22,
                             api_call_23,
                             api_call_24,
                             api_call_25,
                             api_call_26,
                             api_call_27,
                              api_call_28,
                             api_call_29,
                             api_call_30,
                             api_call_31,
                              api_call_32], sort=False, ignore_index=True)

In [72]:
df_clinic_bcn.head()

,Unnamed: 0,link,rating,date,source,review_id,user.name,user.link,user.contributor_id,user.thumbnail,user.reviews,user.photos,snippet,user.local_guide,extracted_snippet.original,extracted_snippet.translated,likes,images,details.también_una_vez_le_pregunté_que_qué_es_lo_que_podía_hacer_para_que_no_me_doliera_tanto_el_ojo_al_llorar_y_me_dijo_literalmente
0,0,https://www.google.com/maps/reviews/data=!4m8!...,5.0,6 hours ago,Google,ChdDSUhNMG9nS0VJQ0FnSUM5NXFPSGlBRRAB,Anna Sánchez Cantos,https://www.google.com/maps/contrib/1019976366...,101997636678627602970,https://lh3.googleusercontent.com/a-/ALV-UjVHn...,30.0,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,https://www.google.com/maps/reviews/data=!4m8!...,5.0,a day ago,Google,ChdDSUhNMG9nS0VJQ0FnSUM5clBfaTRBRRAB,Edgar Rivas,https://www.google.com/maps/contrib/1113180793...,111318079368708427573,https://lh3.googleusercontent.com/a/ACg8ocKltx...,5.0,NaN,Todas las personas que se quejan y dan una est...,True,Todas las personas que se quejan y dan una est...,All the people who complain and give a star ha...,NaN,NaN,NaN
2,2,https://www.google.com/maps/reviews/data=!4m8!...,5.0,3 days ago,Google,ChZDSUhNMG9nS0VJQ0FnSUM5dU5XZUtREAE,Xavier Font,https://www.google.com/maps/contrib/1124131590...,112413159013101135309,https://lh3.googleusercontent.com/a/ACg8ocIRtR...,311.0,416.0,"Hospital con especialistas muy cualificados , ...",True,"Hospital con especialistas muy cualificados , ...","Hospital with highly qualified specialists, a ...",NaN,NaN,NaN
3,3,https://www.google.com/maps/reviews/data=!4m8!...,1.0,5 days ago,Google,ChZDSUhNMG9nS0VJQ0FnSUM5b1B2M0tnEAE,rul house,https://www.google.com/maps/contrib/1001760744...,100176074432280613551,https://lh3.googleusercontent.com/a-/ALV-UjVjL...,101.0,132.0,Recientemente mi pareja a estado ingresada aqu...,NaN,Recientemente mi pareja a estado ingresada aqu...,Recently my partner has been admitted here for...,1.0,NaN,NaN
4,4,https://www.google.com/maps/reviews/data=!4m8!...,5.0,6 days ago,Google,ChZDSUhNMG9nS0VJQ0FnSURkMV9qaVJREAE,Anna Mata Gonzalez,https://www.google.com/maps/contrib/1047117496...,104711749677627984762,https://lh3.googleusercontent.com/a-/ALV-UjWPW...,47.0,1.0,A mí siempre me han atendido estupendamente en...,True,A mí siempre me han atendido estupendamente en...,I have always been treated wonderfully at the ...,NaN,NaN,NaN

In [73]:
df_clinic_bcn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 19 columns):
 #   Column                                                                                                                                  Non-Null Count  Dtype
---  ------                                                                                                                                  --------------  -----
 0   Unnamed: 0                                                                                                                              320 non-null    int64
 1   link                                                                                                                                    320 non-null    object
 2   rating                                                                                                                                  320 non-null    float64
 3   date                                                                                                                                    320 non-null    object
 4   source                                                                                                                                  320 non-null    object
 5   review_id                                                                                                                               320 non-null    object
 6   user.name                                                                                                                               320 non-null    object
 7   user.link                                                                                                                               320 non-null    object
 8   user.contributor_id                                                                                                                     320 non-null    object
 9   user.thumbnail                                                                                                                          320 non-null    object
 10  user.reviews                                                                                                                            316 non-null    float64
 11  user.photos                                                                                                                             170 non-null    float64
 12  snippet                                                                                                                                 273 non-null    object
 13  user.local_guide                                                                                                                        121 non-null    object
 14  extracted_snippet.original                                                                                                              248 non-null    object
 15  extracted_snippet.translated                                                                                                            248 non-null    object
 16  likes                                                                                                                                   174 non-null    float64
 17  images                                                                                                                                  18 non-null     object
 18  details.también_una_vez_le_pregunté_que_qué_es_lo_que_podía_hacer_para_que_no_me_doliera_tanto_el_ojo_al_llorar_y_me_dijo_literalmente  1 non-null      object
dtypes: float64(4), int64(1), object(14)
memory usage: 47.6+ KB

In [74]:
drop_cols = ['Unnamed: 0',
             'link',
             'images',
            'source',
            'review_id',
            'user.name',
            'user.link',
            'user.contributor_id',
            'user.thumbnail',
            'user.reviews',
            'extracted_snippet.original',
            'extracted_snippet.translated', 
            'user.photos',
            #'response.extracted_snippet.original', 
            #'response.extracted_snippet.translated',
            'likes',
            'user.local_guide',
            'details.también_una_vez_le_pregunté_que_qué_es_lo_que_podía_hacer_para_que_no_me_doliera_tanto_el_ojo_al_llorar_y_me_dijo_literalmente']
            #'details.nota_editada',
            #'details.en_resumen',
            #'details.no_me_deja_responderos_por_lo_que_edito_22_08_23_10']

In [75]:
df_clinic_bcn = df_clinic_bcn.drop(columns=[columna for columna in drop_cols if columna in df_clinic_bcn.columns], errors='ignore')
print(f'Eliminadas las columnas innecesarias del DataFrame. Ahora cuenta con las siguientes columnas: ', len(df_clinic_bcn.columns))

Eliminadas las columnas innecesarias del DataFrame. Ahora cuenta con las siguientes columnas:  3

In [76]:
df_clinic_bcn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   rating   320 non-null    float64
 1   date     320 non-null    object
 2   snippet  273 non-null    object
dtypes: float64(1), object(2)
memory usage: 7.6+ KB

In [77]:
df_clinic_bcn['date'].unique()

array(['6 hours ago', 'a day ago', '3 days ago', '5 days ago',
       '6 days ago', 'a week ago', '2 weeks ago', '3 weeks ago',
       '4 weeks ago', 'a month ago', '2 months ago', '3 months ago',
       '4 months ago', '5 months ago', '6 months ago', '7 months ago',
       '8 months ago', '9 months ago', '10 months ago', '11 months ago',
       'a year ago'], dtype=object)

In [78]:
fechas = {
    #'an hour ago': '2024-02-01',
    '6 hours ago': '2024-02-12',
    'a day ago': '2024-02-01',
    '3 days ago': '2024-02-01',
    '5 days ago': '2024-02-01',
    '6 days ago': '2024-02-01',
    'a week ago': '2024-02-01',
    '2 weeks ago': '2024-02-01',
    '3 weeks ago': '2024-02-01',
    '4 weeks ago': '2024-02-01',
    'a month ago': '2024-01-01',
    '2 months ago': '2023-12-01',
    '3 months ago': '2023-11-01',
    '4 months ago': '2023-10-01',
    '5 months ago': '2023-09-01',
    '6 months ago': '2023-08-01',
    '7 months ago': '2023-07-01',
    '8 months ago': '2023-06-01',
    '9 months ago': '2023-05-01',
    '10 months ago': '2023-04-01',
    '11 months ago': '2023-03-01',
    'a year ago': 'eliminar'
}

In [79]:
df_clinic_bcn['Fecha'] = df_clinic_bcn['date'].map(fechas).fillna(pd.to_datetime(df_clinic_bcn['date'], errors='coerce'))

In [80]:
df_clinic_bcn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   rating   320 non-null    float64
 1   date     320 non-null    object
 2   snippet  273 non-null    object
 3   Fecha    320 non-null    object
dtypes: float64(1), object(3)
memory usage: 10.1+ KB

In [81]:
df_clinic_bcn = df_clinic_bcn[df_clinic_bcn['Fecha'] != 'eliminar']

In [82]:
df_clinic_bcn.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 312 entries, 0 to 311
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   rating   312 non-null    float64
 1   date     312 non-null    object
 2   snippet  266 non-null    object
 3   Fecha    312 non-null    object
dtypes: float64(1), object(3)
memory usage: 12.2+ KB

In [84]:
df_clinic_bcn = df_clinic_bcn.assign(Ciudad='Barcelona', Dirección='Calle de Villarroel, 17', Establecimiento='Hospital Clínico de Barcelona', CP='08036')

In [86]:
df_clinic_bcn.head()

,rating,date,snippet,Fecha,Ciudad,Dirección,Establecimiento,CP
0,5.0,6 hours ago,NaN,2024-02-12,Barcelona,"Calle de Villarroel, 17",Hospital Clínico de Barcelona,08036
1,5.0,a day ago,Todas las personas que se quejan y dan una est...,2024-02-01,Barcelona,"Calle de Villarroel, 17",Hospital Clínico de Barcelona,08036
2,5.0,3 days ago,"Hospital con especialistas muy cualificados , ...",2024-02-01,Barcelona,"Calle de Villarroel, 17",Hospital Clínico de Barcelona,08036
3,1.0,5 days ago,Recientemente mi pareja a estado ingresada aqu...,2024-02-01,Barcelona,"Calle de Villarroel, 17",Hospital Clínico de Barcelona,08036
4,5.0,6 days ago,A mí siempre me han atendido estupendamente en...,2024-02-01,Barcelona,"Calle de Villarroel, 17",Hospital Clínico de Barcelona,08036

In [87]:
df_clinic_bcn.drop('date', axis=1, inplace=True)

In [88]:
df_clinic_bcn.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 312 entries, 0 to 311
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   rating           312 non-null    float64
 1   snippet          266 non-null    object
 2   Fecha            312 non-null    object
 3   Ciudad           312 non-null    object
 4   Dirección        312 non-null    object
 5   Establecimiento  312 non-null    object
 6   CP               312 non-null    object
dtypes: float64(1), object(6)
memory usage: 19.5+ KB

In [89]:
df_clinic_bcn['rating'] = df_clinic_bcn['rating'].astype('int64')

In [90]:
df_clinic_bcn['Fecha'] = pd.to_datetime(df_clinic_bcn['Fecha'])

In [91]:
df_clinic_bcn.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 312 entries, 0 to 311
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   rating           312 non-null    int64
 1   snippet          266 non-null    object
 2   Fecha            312 non-null    datetime64[ns]
 3   Ciudad           312 non-null    object
 4   Dirección        312 non-null    object
 5   Establecimiento  312 non-null    object
 6   CP               312 non-null    object
dtypes: datetime64[ns](1), int64(1), object(5)
memory usage: 19.5+ KB

# Hosp. Univ. Vall d'Hebrón

In [92]:
api_call_1 = pd.read_csv('./vall/vall_1.csv')
api_call_2 = pd.read_csv('./vall/vall_2.csv')
api_call_3 = pd.read_csv('./vall/vall_3.csv')
api_call_4 = pd.read_csv('./vall/vall_4.csv')
api_call_5 = pd.read_csv('./vall/vall_5.csv')
api_call_6 = pd.read_csv('./vall/vall_6.csv')
api_call_7 = pd.read_csv('./vall/vall_7.csv')
api_call_8 = pd.read_csv('./vall/vall_8.csv')
api_call_9 = pd.read_csv('./vall/vall_9.csv')
api_call_10 = pd.read_csv('./vall/vall_10.csv')
api_call_11 = pd.read_csv('./vall/vall_11.csv')
api_call_12 = pd.read_csv('./vall/vall_12.csv')
api_call_13 = pd.read_csv('./vall/vall_13.csv')
api_call_14 = pd.read_csv('./vall/vall_14.csv')
api_call_15 = pd.read_csv('./vall/vall_15.csv')
api_call_16 = pd.read_csv('./vall/vall_16.csv')
api_call_17 = pd.read_csv('./vall/vall_17.csv')
api_call_18 = pd.read_csv('./vall/vall_18.csv')

In [93]:
df_vall = pd.concat([api_call_1,
                            api_call_2,
                            api_call_3,
                            api_call_4,
                            api_call_5,
                            api_call_6,
                            api_call_7,
                            api_call_8,
                            api_call_9,
                            api_call_10,
                            api_call_11,
                            api_call_12,
                            api_call_13,
                             api_call_14,
                             api_call_15,
                             api_call_16,
                             api_call_17,
                             api_call_18], sort=False, ignore_index=True)

In [94]:
df_vall.head()

,Unnamed: 0,link,rating,date,source,review_id,snippet,user.name,user.link,user.contributor_id,user.thumbnail,user.reviews,extracted_snippet.original,extracted_snippet.translated,likes,user.local_guide,user.photos,details.gracias_hijos_si_mi_ex_reseñas_de_él_léanlas_me_salieron_sin_buscar,details.me_decía,images
0,0,https://www.google.com/maps/reviews/data=!4m8!...,1.0,3 hours ago,Google,ChdDSUhNMG9nS0VJQ0FnSUM5MXRXTy1BRRAB,"Impossible contactar per telèfon, una vergonya",Olga Barbens,https://www.google.com/maps/contrib/1064624815...,106462481573079367465,https://lh3.googleusercontent.com/a/ACg8ocIJaq...,28.0,"Impossible contactar per telèfon, una vergonya","Impossible to contact by phone, a shame",NaN,NaN,NaN,NaN,NaN,NaN
1,1,https://www.google.com/maps/reviews/data=!4m8!...,1.0,a day ago,Google,ChdDSUhNMG9nS0VJQ0FnSUM5Mm9iZzNBRRAB,Tres horas en urgencias y la gente que venían ...,Jonathan,https://www.google.com/maps/contrib/1061917329...,106191732952017377604,https://lh3.googleusercontent.com/a-/ALV-UjXNH...,27.0,Tres horas en urgencias y la gente que venían ...,Three hours in the emergency room and the peop...,1.0,True,5.0,NaN,NaN,NaN
2,2,https://www.google.com/maps/reviews/data=!4m8!...,1.0,a day ago,Google,ChZDSUhNMG9nS0VJQ0FnSUM5ekpfRFd3EAE,"Fatallllllll, llegue con mi mamá a las 2 con d...",Belen Martinez,https://www.google.com/maps/contrib/1039392870...,103939287014998532387,https://lh3.googleusercontent.com/a/ACg8ocL_PK...,4.0,"Fatallllllll, llegue con mi mamá a las 2 con d...","Fatallllllll, I arrived with my mother at 2 o'...",1.0,NaN,NaN,NaN,NaN,NaN
3,3,https://www.google.com/maps/reviews/data=!4m8!...,5.0,2 days ago,Google,ChdDSUhNMG9nS0VJQ0FnSUM5akoydmtnRRAB,NaN,Jose Varela,https://www.google.com/maps/contrib/1034083614...,103408361489345085761,https://lh3.googleusercontent.com/a/ACg8ocKxCD...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,https://www.google.com/maps/reviews/data=!4m8!...,5.0,3 days ago,Google,ChZDSUhNMG9nS0VJQ0FnSUM5LU4tZ1dnEAE,Gracias a todo el servicio de urgencias por vu...,Jordi V,https://www.google.com/maps/contrib/1035389676...,103538967653672541164,https://lh3.googleusercontent.com/a/ACg8ocKwJD...,16.0,Gracias a todo el servicio de urgencias por vu...,Thank you to the entire emergency service for ...,NaN,True,1.0,NaN,NaN,NaN

In [95]:
df_vall.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 20 columns):
 #   Column                                                                       Non-Null Count  Dtype
---  ------                                                                       --------------  -----
 0   Unnamed: 0                                                                   180 non-null    int64
 1   link                                                                         180 non-null    object
 2   rating                                                                       180 non-null    float64
 3   date                                                                         180 non-null    object
 4   source                                                                       180 non-null    object
 5   review_id                                                                    180 non-null    object
 6   snippet                                                                      155 non-null    object
 7   user.name                                                                    180 non-null    object
 8   user.link                                                                    180 non-null    object
 9   user.contributor_id                                                          180 non-null    object
 10  user.thumbnail                                                               180 non-null    object
 11  user.reviews                                                                 178 non-null    float64
 12  extracted_snippet.original                                                   150 non-null    object
 13  extracted_snippet.translated                                                 150 non-null    object
 14  likes                                                                        104 non-null    float64
 15  user.local_guide                                                             64 non-null     object
 16  user.photos                                                                  85 non-null     float64
 17  details.gracias_hijos_si_mi_ex_reseñas_de_él_léanlas_me_salieron_sin_buscar  1 non-null      object
 18  details.me_decía                                                             1 non-null      object
 19  images                                                                       6 non-null      object
dtypes: float64(4), int64(1), object(15)
memory usage: 28.2+ KB

In [96]:
drop_cols = ['Unnamed: 0',
                 'link',
                'source',
                'review_id',
                'user.name',
                'user.link',
                'user.contributor_id',
                'user.thumbnail',
             'user.local_guide',
                'user.reviews',
             'user.photos',
                'extracted_snippet.original',
                'extracted_snippet.translated',
                'likes',
                'details.gracias_hijos_si_mi_ex_reseñas_de_él_léanlas_me_salieron_sin_buscar',
                'details.me_decía',
            'images']
                #'details.no_me_deja_responderos_por_lo_que_edito_22_08_23_10']
df_vall = df_vall.drop(columns=[columna for columna in drop_cols if columna in df_vall.columns], errors='ignore')
print(f'Eliminadas las columnas innecesarias del DataFrame. Ahora cuenta con las siguientes columnas: ', len(df_vall.columns))

Eliminadas las columnas innecesarias del DataFrame. Ahora cuenta con las siguientes columnas:  3

In [97]:
df_vall.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   rating   180 non-null    float64
 1   date     180 non-null    object
 2   snippet  155 non-null    object
dtypes: float64(1), object(2)
memory usage: 4.3+ KB

In [98]:
df_vall['date'].unique()

array(['3 hours ago', 'a day ago', '2 days ago', '3 days ago',
       '4 days ago', '6 days ago', 'a week ago', '2 weeks ago',
       '3 weeks ago', 'a month ago', '2 months ago', '3 months ago',
       '4 months ago', '5 months ago', '6 months ago', '7 months ago',
       '8 months ago', '9 months ago', '10 months ago', '11 months ago',
       'a year ago'], dtype=object)

In [99]:
fechas = {
    '3 hours ago': '2024-02-12',
    'a day ago': '2024-02-01',
    '2 days ago': '2024-02-01',
    '3 days ago': '2024-02-01',
    '4 days ago': '2024-02-01',
    '6 days ago': '2024-02-01',
    'a week ago': '2024-02-01',
    '2 weeks ago': '2024-02-01',
    '3 weeks ago': '2024-02-01',
    #'4 weeks ago': '2024-02-01',
    'a month ago': '2024-01-01',
    '2 months ago': '2023-12-01',
    '3 months ago': '2023-11-01',
    '4 months ago': '2023-10-01',
    '5 months ago': '2023-09-01',
    '6 months ago': '2023-08-01',
    '7 months ago': '2023-07-01',
    '8 months ago': '2023-06-01',
    '9 months ago': '2023-05-01',
    '10 months ago': '2023-04-01',
    '11 months ago': '2023-03-01',
    'a year ago': 'eliminar'
}

In [100]:
df_vall['Fecha'] = df_vall['date'].map(fechas).fillna(pd.to_datetime(df_vall['date'], errors='coerce'))

In [101]:
df_vall.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   rating   180 non-null    float64
 1   date     180 non-null    object
 2   snippet  155 non-null    object
 3   Fecha    180 non-null    object
dtypes: float64(1), object(3)
memory usage: 5.8+ KB

In [102]:
df_vall = df_vall[df_vall['Fecha'] != 'eliminar']

In [103]:
df_vall.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 176 entries, 0 to 175
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   rating   176 non-null    float64
 1   date     176 non-null    object
 2   snippet  151 non-null    object
 3   Fecha    176 non-null    object
dtypes: float64(1), object(3)
memory usage: 6.9+ KB

In [104]:
df_vall.drop('date', axis=1, inplace=True)

In [105]:
df_vall.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 176 entries, 0 to 175
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   rating   176 non-null    float64
 1   snippet  151 non-null    object
 2   Fecha    176 non-null    object
dtypes: float64(1), object(2)
memory usage: 5.5+ KB

In [106]:
df_vall['rating'] = df_vall['rating'].astype('int64')

In [107]:
df_vall['Fecha'] = pd.to_datetime(df_vall['Fecha'])

In [108]:
df_vall.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 176 entries, 0 to 175
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   rating   176 non-null    int64
 1   snippet  151 non-null    object
 2   Fecha    176 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 5.5+ KB

In [109]:
df_vall = df_vall.assign(Ciudad='Barcelona', Dirección="Passeig de la Vall d'Hebron", Establecimiento='Hospital Universitario Valle de Hebrón', CP='08035')

In [110]:
df_vall.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 176 entries, 0 to 175
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   rating           176 non-null    int64
 1   snippet          151 non-null    object
 2   Fecha            176 non-null    datetime64[ns]
 3   Ciudad           176 non-null    object
 4   Dirección        176 non-null    object
 5   Establecimiento  176 non-null    object
 6   CP               176 non-null    object
dtypes: datetime64[ns](1), int64(1), object(5)
memory usage: 11.0+ KB

In [111]:
df_vall.tail()

,rating,snippet,Fecha,Ciudad,Dirección,Establecimiento,CP
171,5,Enca tadora muy amables y profesionales,2023-03-01,Barcelona,Passeig de la Vall d'Hebron,Hospital Universitario Valle de Hebrón,08035
172,5,Me sorprende lo bien organizado que está el mó...,2023-03-01,Barcelona,Passeig de la Vall d'Hebron,Hospital Universitario Valle de Hebrón,08035
173,5,És del millor que tenim. No hi perdem mai. Grà...,2023-03-01,Barcelona,Passeig de la Vall d'Hebron,Hospital Universitario Valle de Hebrón,08035
174,1,Atenció telefònica nefasta. Tel. 934893000. Se...,2023-03-01,Barcelona,Passeig de la Vall d'Hebron,Hospital Universitario Valle de Hebrón,08035
175,1,"La atención telefónica es pésima, te tratan de...",2023-03-01,Barcelona,Passeig de la Vall d'Hebron,Hospital Universitario Valle de Hebrón,08035

# Paso final: un único Excel con todos

In [112]:
df_clinic_bcn.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 312 entries, 0 to 311
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   rating           312 non-null    int64
 1   snippet          266 non-null    object
 2   Fecha            312 non-null    datetime64[ns]
 3   Ciudad           312 non-null    object
 4   Dirección        312 non-null    object
 5   Establecimiento  312 non-null    object
 6   CP               312 non-null    object
dtypes: datetime64[ns](1), int64(1), object(5)
memory usage: 19.5+ KB

In [113]:
df_doce_octubre.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 337 entries, 0 to 343
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   rating           337 non-null    int64
 1   snippet          254 non-null    object
 2   Fecha            337 non-null    datetime64[ns]
 3   Ciudad           337 non-null    object
 4   Dirección        337 non-null    object
 5   Establecimiento  337 non-null    object
 6   CP               337 non-null    int64
dtypes: datetime64[ns](1), int64(2), object(4)
memory usage: 21.1+ KB

In [114]:
df_vall.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 176 entries, 0 to 175
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   rating           176 non-null    int64
 1   snippet          151 non-null    object
 2   Fecha            176 non-null    datetime64[ns]
 3   Ciudad           176 non-null    object
 4   Dirección        176 non-null    object
 5   Establecimiento  176 non-null    object
 6   CP               176 non-null    object
dtypes: datetime64[ns](1), int64(1), object(5)
memory usage: 11.0+ KB

In [115]:
df_full_hospitals = pd.concat([df_clinic_bcn,
                              df_doce_octubre,
                              df_vall], sort=False, ignore_index=True)

In [116]:
df_full_hospitals

,rating,snippet,Fecha,Ciudad,Dirección,Establecimiento,CP
0,5,NaN,2024-02-12,Barcelona,"Calle de Villarroel, 17",Hospital Clínico de Barcelona,08036
1,5,Todas las personas que se quejan y dan una est...,2024-02-01,Barcelona,"Calle de Villarroel, 17",Hospital Clínico de Barcelona,08036
2,5,"Hospital con especialistas muy cualificados , ...",2024-02-01,Barcelona,"Calle de Villarroel, 17",Hospital Clínico de Barcelona,08036
3,1,Recientemente mi pareja a estado ingresada aqu...,2024-02-01,Barcelona,"Calle de Villarroel, 17",Hospital Clínico de Barcelona,08036
4,5,A mí siempre me han atendido estupendamente en...,2024-02-01,Barcelona,"Calle de Villarroel, 17",Hospital Clínico de Barcelona,08036
...,...,...,...,...,...,...,...
820,5,Enca tadora muy amables y profesionales,2023-03-01,Barcelona,Passeig de la Vall d'Hebron,Hospital Universitario Valle de Hebrón,08035
821,5,Me sorprende lo bien organizado que está el mó...,2023-03-01,Barcelona,Passeig de la Vall d'Hebron,Hospital Universitario Valle de Hebrón,08035
822,5,És del millor que tenim. No hi perdem mai. Grà...,2023-03-01,Barcelona,Passeig de la Vall d'Hebron,Hospital Universitario Valle de Hebrón,08035
823,1,Atenció telefònica nefasta. Tel. 934893000. Se...,2023-03-01,Barcelona,Passeig de la Vall d'Hebron,Hospital Universitario Valle de Hebrón,08035
824,1,"La atención telefónica es pésima, te tratan de...",2023-03-01,Barcelona,Passeig de la Vall d'Hebron,Hospital Universitario Valle de Hebrón,08035

In [117]:
len(df_clinic_bcn)+len(df_doce_octubre)+len(df_vall)

825

In [118]:
len(df_full_hospitals)

825

In [119]:
df_full_hospitals.to_excel('../reviews/hosp_alta.xlsx')